---
title: "Dorothea_diffexp.Rmd"
author: "Christian Heyer"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, dev = "png",
  fig.width = 12, fig.height = 12
)
if (!require(dorothea)) {
  BiocManager::install("dorothea")
}
library(dorothea)
library(decoupleR)
library(BiocParallel)
library(dplyr)
library(viper)
library(RColorBrewer)
if (!require(RNAscripts)) {
  devtools::install("./scripts/RNAscripts", upgrade = "never")
}
library(RNAscripts)
library(ggplot2)
library(readr)
library(ComplexHeatmap)
library(DESeq2)
library(purrr)
library(tidyverse)
if (TRUE) {
  write(str(snakemake), file = stderr())
  dds_path <- snakemake@input[["dds_obj"]]
  cond_var <- snakemake@wildcards[["condition"]]
  diffexp_tb_path <- snakemake@input[["table"]]
  fpkm_path <- snakemake@input[["fpkm"]]
  contrast_groups <- snakemake@wildcards[["contrast"]]

  register(MulticoreParam(snakemake@threads))
  contrast_name <- contrast_groups
  plot_path <- snakemake@params[["plot_path"]]
  color_scheme <- snakemake@config[["group_colors"]][[cond_var]]
  organism <- snakemake@config[["organism"]]
} else {
  the_yaml <- yaml::read_yaml("../../../config/STAD.yaml")
  snakedir <- "/Users/heyechri/Documents/software/heyer/multicondition-deseq2-enrichment"
  BASE_ANALYSIS_DIR <- file.path(snakedir, "data/STAD")
  dds_path <- file.path(paste0(BASE_ANALYSIS_DIR), "deseq2/all.rds")
  cond_var <- names(the_yaml$diffexp$contrasts)[2]
  diffexp_tb_path <- file.path(
    paste0(BASE_ANALYSIS_DIR),
    glue::glue("results/diffexp/{cond_var}/{names(the_yaml$diffexp$contrasts[[cond_var]])[1]}.diffexp.tsv")
  )
  fpkm_path <- file.path(BASE_ANALYSIS_DIR, "fpkm/all.tsv")
  contrast_groups <- the_yaml$diffexp$contrasts[[cond_var]][1]
  plot_path <- "."
  register(SerialParam())
  # s_groups<- c("d0-lung", "d15-lung", "d22-lung", "d36-lung", "18m-lung")
  contrast_name <- glue::glue("{contrast_groups[1]} vs {contrast_groups[2]}")

  comp_groups <- the_yaml$comp_groups
  color_scheme <- the_yaml$group_colors[[cond_var]]
  organism <- "Homo sapiens"
}
dir.create(plot_path, recursive = T)
```


## Using decoupler

Using the decoupler Framework we infer TF activities along the network of TF
activities provided by dorothea. 

```{r read data}
dds_obj <- readRDS(dds_path)
diffexp_tb <- read_tsv(diffexp_tb_path,
  col_names = c(
    "gene_id",
    "baseMean",
    "logFoldChange",
    "lfcSE", "stat",
    "pvalue", "padj"
  ),
  skip = 1
)
Normalized_counts <- getVarianceStabilizedData(dds_obj)
# Normalized_counts<- assay(vst(dds_obj,blind = FALSE))
fpkm <- read_tsv(fpkm_path)
filer <- fpkm %>%
  dplyr::filter(gene %in% rownames(Normalized_counts)) %>%
  dplyr::filter(!duplicated(gname))

joined_df <- join_tables(diffexp_tb, filer) %>% dplyr::filter(!duplicated(gname))
Normalized_counts <- Normalized_counts[filer$gene, ]

rownames(Normalized_counts) <- filer$gname

joined_df %>%
  dplyr::select(gname, stat) %>%
  dplyr::filter(!is.na(stat)) %>%
  tibble::column_to_rownames(var = "gname") %>%
  as.matrix() -> diffexp_matrix
regulons <- dorothea_mm %>% filter(confidence %in% c("A", "B", "C"))
```

```{r}
if (organism == "Mus musculus") {
  org_name <- "mouse"
} else if (organism == "Homo sapiens") {
  org_name <- "human"
} else {
  stop("Organism not supported. Please set Mus musculus or Homo sapiens in the config")
}
net <- get_dorothea(organism = org_name, levels = c("A", "B", "C"))
deg <- joined_df %>%
  dplyr::select(gname, logFoldChange, stat, padj) %>%
  dplyr::filter(!is.na(stat)) %>%
  mutate(padj = tidyr::replace_na(padj, 1)) %>%
  tibble::column_to_rownames(var = "gname") %>%
  as.matrix() -> diffexp_matrix
design <- dds_obj@colData
sample_acts <- run_wmean(
  mat = Normalized_counts, network = net, .source = "source", .target = "target",
  .mor = "mor", times = 1000, minsize = 2
)
n_tfs <- 30

# Transform to wide matrix
sample_acts_mat <- sample_acts %>%
  filter(statistic == "norm_wmean") %>%
  pivot_wider(
    id_cols = "condition", names_from = "source",
    values_from = "score"
  ) %>%
  tibble::column_to_rownames("condition") %>%
  as.matrix()

# Get top tfs with more variable means across clusters
tfs <- sample_acts %>%
  group_by(source) %>%
  dplyr::summarise(std = sd(score)) %>%
  arrange(-abs(std)) %>%
  head(n_tfs, n = 30) %>%
  pull(source)
sample_acts_mat <- sample_acts_mat[, tfs]

# Scale per sample
sample_acts_mat <- scale(sample_acts_mat, scale = F)

# Choose color palette
palette_length <- 100
my_color <- colorRampPalette(c("Darkblue", "white", "red"))(palette_length)

my_breaks <- c(
  seq(-3, 0, length.out = ceiling(palette_length / 2) + 1),
  seq(0.05, 3, length.out = floor(palette_length / 2))
)

if (!is.null(color_scheme)) {
  ha <- rowAnnotation(
    group = as.character(dds_obj@colData[, cond_var]),
    col = list(
      group =
        as_vector(color_scheme)
    )
  )
} else {
  ha <- rowAnnotation(group = as.character(dds_obj@colData[, cond_var]))
}


# Plot
ComplexHeatmap::Heatmap(sample_acts_mat,
  clustering_method_rows = "average",
  clustering_method_columns = "average",
  right_annotation = ha,
  heatmap_legend_param = list(title = "score")
)
```

```{r}
contrast_acts <- run_wmean(
  mat = deg[, "stat", drop = FALSE],
  net = net, .source = "source", .target = "target",
  .mor = "mor", times = 1000, minsize = 3
)
contrast_acts
f_contrast_acts <- contrast_acts %>%
  filter(statistic == "norm_wmean") %>%
  mutate(rnk = NA)

# Filter top TFs in both signs
msk <- f_contrast_acts$score > 0
f_contrast_acts[msk, "rnk"] <- rank(-f_contrast_acts[msk, "score"])
f_contrast_acts[!msk, "rnk"] <- rank(-abs(f_contrast_acts[!msk, "score"]))
tfs <- f_contrast_acts %>%
  arrange(rnk) %>%
  head(n_tfs) %>%
  pull(source)
f_contrast_acts <- f_contrast_acts %>%
  filter(source %in% tfs)

# Plot
ggplot(f_contrast_acts, aes(x = reorder(source, score), y = score)) +
  geom_bar(aes(fill = score), stat = "identity") +
  scale_fill_gradient2(
    low = "darkblue", high = "indianred",
    mid = "whitesmoke", midpoint = 0
  ) +
  theme_minimal() +
  theme(
    axis.title = element_text(face = "bold", size = 12),
    axis.text.x =
      element_text(angle = 45, hjust = 1, size = 10, face = "bold"),
    axis.text.y = element_text(size = 10, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  xlab("TFs")
```










## Legacy Dorothea VIPER plots

Here, we also have dorothea enrichments as described in the original dorothea publications.
Instead of using decoupleRs wmean we use viper for inferring TF activites. 

```{r Viper Dorothea, echo=FALSE}
viper_net <- net
colnames(viper_net) <- colnames(dorothea_mm)
tf_activities_stat <- dorothea::run_viper(diffexp_matrix, viper_net,
  options = list(
    minsize = 5, eset.filter = FALSE,
    cores = 1, verbose = F, nes = TRUE
  )
)

tf_activities_stat_top25 <- tf_activities_stat %>%
  as.data.frame() %>%
  rownames_to_column(var = "GeneID") %>%
  dplyr::rename(NES = "stat") %>%
  dplyr::top_n(25, wt = abs(NES)) %>%
  dplyr::arrange(NES) %>%
  dplyr::mutate(GeneID = factor(GeneID))

NES_plot <- ggplot(tf_activities_stat_top25, aes(x = reorder(GeneID, NES), y = NES)) +
  geom_bar(aes(fill = NES), stat = "identity") +
  scale_fill_gradient2(
    low = "darkblue", high = "indianred",
    mid = "whitesmoke", midpoint = 0
  ) +
  theme_minimal() +
  theme(
    axis.title = element_text(face = "bold", size = 12),
    axis.text.x =
      element_text(angle = 45, hjust = 1, size = 10, face = "bold"),
    axis.text.y = element_text(size = 10, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  xlab("Transcription Factors") +
  ggtitle(contrast_name)
ggsave(filename = file.path(plot_path, glue::glue("{contrast_name}_NES_plot.svg")), NES_plot)
NES_plot
```

```{r, eval = F}
tf_activities_counts <-
  dorothea::run_viper(Normalized_counts, regulons,
    options = list(
      minsize = 5, eset.filter = FALSE,
      cores = 1, verbose = FALSE, method = c("scale")
    )
  )

tf_activities_counts_filter <- tf_activities_counts %>%
  as.data.frame() %>%
  rownames_to_column(var = "GeneID") %>%
  dplyr::filter(GeneID %in% tf_activities_stat_top25$GeneID) %>%
  column_to_rownames(var = "GeneID") %>%
  as.matrix()
tf_activities_vector <- as.vector(tf_activities_counts_filter)

paletteLength <- 100

ha <- HeatmapAnnotation(
  group = dds_obj@colData$condition,
  col = list(
    group =
      as_vector(color_scheme)
  )
)

dorothea_hmap <- ComplexHeatmap::Heatmap(tf_activities_counts_filter,
  name = glue::glue("NES"),
  top_annotation = ha,
  show_column_names = F
)

save_cheatmap_svg(x = dorothea_hmap, filename = file.path(plot_path, glue::glue("{contrast_name}_dorothea.svg")))
dorothea_hmap
```


```{r, eval = F}
tf_activities_CARNIVALinput <- tf_activities_stat %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "TF")
write_csv(tf_activities_CARNIVALinput, "../results/TFActivity_CARNIVALinput.csv")
```
